(() => {
  'use strict';
  const BOOK_KEY='tcci.v2';
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const safeJSON=(s,f)=>{try{return JSON.parse(s)}catch{return f}};
  const state=safeJSON(localStorage.getItem(BOOK_KEY),{current:null,completed:{},favorites:{},notes:{},font:1,spacing:1,theme:'auto'});
  const save=()=>localStorage.setItem(BOOK_KEY,JSON.stringify(state));
  const chapter=document.body.dataset.chapter||''; const slug=document.body.dataset.slug||'';
  if(chapter){ state.current={chapter:Number(chapter),slug,url:location.pathname+location.hash,scroll:0,updated:Date.now()}; save(); }
  function applyPrefs(){document.documentElement.style.setProperty('--reader-size',`${18*state.font}px`);document.documentElement.style.setProperty('--reader-leading',String(1.68*state.spacing));if(state.theme==='auto')document.documentElement.removeAttribute('data-theme');else document.documentElement.dataset.theme=state.theme}applyPrefs();
  function updateProgress(){const el=$('[data-chapter-progress]');if(!el)return;const max=document.documentElement.scrollHeight-innerHeight;const pct=max>0?Math.max(0,Math.min(100,scrollY/max*100)):0;el.style.width=pct+'%';if(chapter&&state.current){state.current.scroll=pct;save()}}addEventListener('scroll',updateProgress,{passive:true});updateProgress();
  const bookProgress=$('[data-book-progress]');if(bookProgress){const done=Object.values(state.completed).filter(Boolean).length;bookProgress.textContent=`${done} de 28 concluídos`}
  const complete=$('[data-complete]');if(complete&&chapter){const render=()=>{const yes=!!state.completed[chapter];complete.dataset.complete=yes;complete.querySelector('[data-complete-label]').textContent=yes?'Capítulo concluído':'Marcar como concluído'};complete.addEventListener('click',e=>{if(e.target.closest('button')){state.completed[chapter]=!state.completed[chapter];save();render();if(bookProgress){const done=Object.values(state.completed).filter(Boolean).length;bookProgress.textContent=`${done} de 28 concluídos`}}});render()}
  const fav=$('[data-favorite]');if(fav&&chapter){const render=()=>fav.setAttribute('aria-pressed',state.favorites[chapter]?'true':'false');fav.addEventListener('click',()=>{state.favorites[chapter]=!state.favorites[chapter];save();render()});render()}
  $$('[data-note-id]').forEach(el=>{const id=el.dataset.noteId;el.value=state.notes[id]||'';let t;el.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>{state.notes[id]=el.value;save();const s=el.closest('.interactive-box')?.querySelector('.autosave');if(s){s.textContent='Salvo neste dispositivo';setTimeout(()=>s.textContent='Salvamento local automático',1200)}},250)})});
  const search=$('[data-search-panel]'),searchInput=$('[data-search-input]'),results=$('[data-search-results]');let index=[];
  async function loadIndex(){if(index.length)return index;const base=document.body.dataset.root||'./';try{const r=await fetch(base+'search-index.json.gz',{cache:'force-cache'});if(!r.ok)throw new Error('search');if(!('DecompressionStream' in window))throw new Error('gzip unsupported');const text=await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).text();index=JSON.parse(text)}catch{try{const r=await fetch(base+'toc.json',{cache:'force-cache'});const rows=await r.json();index=rows.map(x=>({title:x.n+'. '+x.title,url:base+'capitulos/'+x.slug+'/',keywords:x.part,text:x.title+' '+x.part,snippet:'Resultado por título e parte'}))}catch{index=[]}}return index}
  const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function score(q,item){const terms=norm(q).split(/\s+/).filter(Boolean);const t=norm(item.title+' '+(item.keywords||'')+' '+item.text);let sc=0;for(const term of terms){if(norm(item.title).includes(term))sc+=7;if(norm(item.keywords||'').includes(term))sc+=4;const n=t.split(term).length-1;sc+=Math.min(n,5)}return sc}
  async function doSearch(q){if(!results)return;if(q.trim().length<2){results.innerHTML='<p>Digite ao menos dois caracteres.</p>';return}const data=await loadIndex();const ranked=data.map(x=>[score(q,x),x]).filter(x=>x[0]>0).sort((a,b)=>b[0]-a[0]).slice(0,30);results.innerHTML=ranked.length?ranked.map(([s,x])=>`<a class="search-result" href="${x.url}"><strong>${escapeHTML(x.title)}</strong><small>${escapeHTML(x.snippet||'')}</small></a>`).join(''):'<p>Nenhum resultado encontrado.</p>'}
  function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  $$('[data-search-open]').forEach(b=>b.addEventListener('click',async()=>{search?.classList.add('open');search?.setAttribute('aria-hidden','false');await loadIndex();searchInput?.focus()}));$('[data-search-close]')?.addEventListener('click',()=>{search?.classList.remove('open');search?.setAttribute('aria-hidden','true')});searchInput?.addEventListener('input',e=>doSearch(e.target.value));
  const settings=$('[data-settings-panel]');$('[data-settings-open]')?.addEventListener('click',()=>{settings?.classList.add('open');settings?.setAttribute('aria-hidden','false')});$('[data-settings-close]')?.addEventListener('click',()=>{settings?.classList.remove('open');settings?.setAttribute('aria-hidden','true')});$$('[data-font]').forEach(b=>b.addEventListener('click',()=>{state.font=Math.max(.85,Math.min(1.35,state.font+Number(b.dataset.font)));save();applyPrefs()}));$$('[data-spacing]').forEach(b=>b.addEventListener('click',()=>{state.spacing=Number(b.dataset.spacing);save();applyPrefs()}));$$('[data-theme]').forEach(b=>b.addEventListener('click',()=>{state.theme=b.dataset.theme;save();applyPrefs()}));
  const cont=$('[data-continue]');if(cont){if(state.current?.slug){cont.href=`capitulos/${state.current.slug}/`;cont.hidden=false}else cont.hidden=true}
  $$('[data-route]').forEach(el=>{const chapters=(el.dataset.route||'').split(',').filter(Boolean);const done=chapters.filter(n=>state.completed[n]).length;const out=el.querySelector('[data-route-progress]');if(out)out.textContent=`${done}/${chapters.length} concluídos`});
  $('[data-export-notes]')?.addEventListener('click',()=>{const rows=Object.entries(state.notes).filter(([,v])=>v.trim());let md='# Minhas notas — TCC-I na Prática Clínica\n\n';rows.forEach(([k,v])=>md+=`## ${k}\n\n${v.trim()}\n\n`);const blob=new Blob([md],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='minhas-notas-tcci.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
  $('[data-clear-local]')?.addEventListener('click',()=>{if(confirm('Apagar progresso, favoritos e notas salvos neste navegador?')){localStorage.removeItem(BOOK_KEY);location.reload()}});
  $$('figure img').forEach(img=>{img.addEventListener('click',()=>{if(!document.fullscreenElement)img.closest('figure')?.requestFullscreen?.();else document.exitFullscreen?.()})});
  async function buildToc(){const targets=$$('[data-toc-desktop],[data-toc-mobile]');if(!targets.length)return;try{const root=document.body.dataset.root||'./';const r=await fetch(root+'toc.json',{cache:'force-cache'});const data=await r.json();const groups={};data.forEach(x=>(groups[x.part]??=[]).push(x));const html=['<nav aria-label="Sumário do livro"><a href="'+root+'">Início</a><a href="'+root+'introducao/">Como usar</a><a href="'+root+'casos/">Casos</a>'];Object.entries(groups).forEach(([part,items])=>{html.push('<h3>'+escapeHTML(part.replace('PARTE ','Parte '))+'</h3>');items.forEach(x=>html.push('<a class="'+(String(x.n)===chapter?'active':'')+'" href="'+root+'capitulos/'+x.slug+'/"><span class="status-dot '+(state.completed[x.n]?'done':'')+'"></span>'+x.n+'. '+escapeHTML(x.title)+'</a>'))});html.push('<h3>Referência</h3><a href="'+root+'glossario/">Glossário</a><a href="'+root+'referencias/">Referências</a><a href="'+root+'ferramentas/">Ferramentas</a></nav>');targets.forEach(t=>t.innerHTML=html.join(''))}catch{}}
  buildToc();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register((document.body.dataset.root||'./')+'service-worker.js').catch(()=>{});addEventListener('keydown',e=>{if(e.key==='Escape'){search?.classList.remove('open');settings?.classList.remove('open')}})
})();
